set_property SRC_FILE_INFO {cfile:C:/Users/jorda/VivadoProj2023/HW2Q2AA/HW2Q2AA.srcs/constrs_1/new/constraints.xdc rfile:../../../HW2Q2AA.srcs/constrs_1/new/constraints.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K18 [get_ports {gpio_sw_tri_io[0]}]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K19 [get_ports {GPIO_0_0_tri_io[0]}]
