#ifndef XPAR_REMAP_H
#define XPAR_REMAP_H

#include "xparameters.h"

#ifndef XPAR_CPU_CORTEXA9_0_CPU_CLK_FREQ_HZ
#define XPAR_CPU_CORTEXA9_0_CPU_CLK_FREQ_HZ  XPAR_CPU_CORE_CLOCK_FREQ_HZ
#endif

#ifndef XPAR_AXI_DYNCLK_0_S_AXI_LITE_BASEADDR
#define XPAR_AXI_DYNCLK_0_S_AXI_LITE_BASEADDR XPAR_AXI_DYNCLK_0_BASEADDR
#endif

#ifndef XPAR_PS7_UART_1_BASEADDR
#define XPAR_PS7_UART_1_BASEADDR XPAR_XUARTPS_0_BASEADDR
#endif

#ifndef XPAR_AXIVDMA_0_DEVICE_ID
#define XPAR_AXIVDMA_0_DEVICE_ID       XPAR_XAXIVDMA_0_BASEADDR
#endif

#ifndef XPAR_V_TC_IN_DEVICE_ID
#define XPAR_V_TC_IN_DEVICE_ID         XPAR_V_TC_IN_BASEADDR
#endif

#ifndef XPAR_V_TC_OUT_DEVICE_ID
#define XPAR_V_TC_OUT_DEVICE_ID        XPAR_V_TC_OUT_BASEADDR
#endif

#ifndef XPAR_AXI_GPIO_VIDEO_DEVICE_ID
#define XPAR_AXI_GPIO_VIDEO_DEVICE_ID  XPAR_AXI_GPIO_VIDEO_BASEADDR
#endif

#ifdef SDT
#undef  XPAR_SCUGIC_SINGLE_DEVICE_ID
#define XPAR_SCUGIC_SINGLE_DEVICE_ID   XPAR_XSCUGIC_0_BASEADDR

#undef  XPAR_SCUTIMER_DEVICE_ID
#define XPAR_SCUTIMER_DEVICE_ID        XPAR_XSCUTIMER_0_BASEADDR
#endif

#ifndef XPAR_FABRIC_V_TC_IN_IRQ_INTR
#define XPAR_FABRIC_V_TC_IN_IRQ_INTR              (XPAR_FABRIC_V_TC_IN_INTR + 32)
#endif

#ifndef XPAR_FABRIC_AXI_GPIO_VIDEO_IP2INTC_IRPT_INTR
#define XPAR_FABRIC_AXI_GPIO_VIDEO_IP2INTC_IRPT_INTR (XPAR_FABRIC_AXI_GPIO_VIDEO_INTR + 32)
#endif

#endif
