#ifndef XPAR_REMAP_H
#define XPAR_REMAP_H

#include "xparameters.h"
#include "xscugic.h"

#ifndef XPAR_D_AXI_I2S_AUDIO_0_AXI_L_BASEADDR
#define XPAR_D_AXI_I2S_AUDIO_0_AXI_L_BASEADDR  XPAR_D_AXI_I2S_AUDIO_0_BASEADDR
#endif

#ifndef XPAR_IIC_0_BASEADDR
#define XPAR_IIC_0_BASEADDR  XPAR_XIIC_0_BASEADDR
#endif

#ifndef XPAR_AXIDMA_0_DEVICE_ID
#define XPAR_AXIDMA_0_DEVICE_ID  XPAR_XAXIDMA_0_BASEADDR
#endif

#ifndef XPAR_AXI_IIC_0_DEVICE_ID
#define XPAR_AXI_IIC_0_DEVICE_ID  XPAR_XIIC_0_BASEADDR
#endif

#ifndef XPAR_PS7_SCUGIC_0_DEVICE_ID
#define XPAR_PS7_SCUGIC_0_DEVICE_ID  XPAR_XSCUGIC_0_BASEADDR
#endif

#ifndef XPAR_SCUGIC_0_DEVICE_ID
#define XPAR_SCUGIC_0_DEVICE_ID  XPAR_XSCUGIC_0_BASEADDR
#endif

#ifndef XPAR_FABRIC_AXI_IIC_0_IIC2INTC_IRPT_INTR
#define XPAR_FABRIC_AXI_IIC_0_IIC2INTC_IRPT_INTR  (XPAR_FABRIC_XIIC_0_INTR + XSCUGIC_SPI_INT_ID_START)
#endif

#ifndef XPAR_FABRIC_AXI_DMA_0_S2MM_INTROUT_INTR
#define XPAR_FABRIC_AXI_DMA_0_S2MM_INTROUT_INTR  (XPAR_FABRIC_AXI_DMA_0_INTR_1 + XSCUGIC_SPI_INT_ID_START)
#endif

#ifndef XPAR_FABRIC_AXI_DMA_0_MM2S_INTROUT_INTR
#define XPAR_FABRIC_AXI_DMA_0_MM2S_INTROUT_INTR  (XPAR_FABRIC_AXI_DMA_0_INTR + XSCUGIC_SPI_INT_ID_START)
#endif

#ifndef XPAR_FABRIC_AXI_GPIO_0_IP2INTC_IRPT_INTR
#define XPAR_FABRIC_AXI_GPIO_0_IP2INTC_IRPT_INTR  (XPAR_FABRIC_XGPIO_0_INTR + XSCUGIC_SPI_INT_ID_START)
#endif

#ifndef XPAR_PS7_DDR_0_S_AXI_BASEADDR
#define XPAR_PS7_DDR_0_S_AXI_BASEADDR  XPAR_PS7_DDR_0_BASEADDRESS
#endif

#ifndef XPAR_SWITCHES_0_BASEADDR
#define XPAR_SWITCHES_0_BASEADDR  XPAR_XGPIO_0_BASEADDR
#endif

#ifndef XPAR_MIG_7SERIES_0_BASEADDR
#define XPAR_MIG_7SERIES_0_BASEADDR  XPAR_PS7_DDR_0_BASEADDRESS
#endif

#ifndef XPAR_CPU_CORTEXA9_0_CPU_CLK_FREQ_HZ
#define XPAR_CPU_CORTEXA9_0_CPU_CLK_FREQ_HZ  XPAR_CPU_CORE_CLOCK_FREQ_HZ
#endif

// HDMI display: VDMA, VTC, dynclk remaps for SDT compatibility
#ifndef XPAR_AXI_DYNCLK_0_S_AXI_LITE_BASEADDR
#define XPAR_AXI_DYNCLK_0_S_AXI_LITE_BASEADDR XPAR_AXI_DYNCLK_0_BASEADDR
#endif

#ifndef XPAR_AXIVDMA_0_DEVICE_ID
#define XPAR_AXIVDMA_0_DEVICE_ID       XPAR_XAXIVDMA_0_BASEADDR
#endif

#ifndef XPAR_V_TC_OUT_DEVICE_ID
#define XPAR_V_TC_OUT_DEVICE_ID        XPAR_V_TC_0_BASEADDR
#endif

#endif
