@echo off
REM ****************************************************************************
REM Vivado (TM) v2025.2.1 (64-bit)
REM
REM Filename    : compile.bat
REM Simulator   : AMD Vivado Simulator
REM Description : Script for compiling the simulation design source files
REM
REM Generated by Vivado on Sun Apr 19 17:21:50 -0700 2026
REM SW Build 6403652 on Thu Mar 19 19:48:24 GMT 2026
REM
REM Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
REM Copyright 2022-2026 Advanced Micro Devices, Inc. All Rights Reserved.
REM
REM usage: compile.bat
REM
REM ****************************************************************************
set SIM_VER_XSIM=
set GCC_VER_XSIM=9.3.0

REM compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -L axi_vip_v1_1_22 -L processing_system7_vip_v1_0_24 -L xilinx_vip -prj sample_buffer_tb_vlog.prj"
call xvlog  --incr --relax -L axi_vip_v1_1_22 -L processing_system7_vip_v1_0_24 -L xilinx_vip -prj sample_buffer_tb_vlog.prj -log xvlog.log
call type xvlog.log > compile.log
if "%errorlevel%"=="1" goto END
if "%errorlevel%"=="0" goto SUCCESS
:END
exit 1
:SUCCESS
exit 0
